Datasets:
  train:
    root: ./DATA/MVTec_AD/
    type: MVTec
    split: 0.8
  eval:
    root: ./DATA/MVTec_AD/
    type: MVTec
  imagenet:
    root: ./DATA/ImageNet/
    type: ImageNet
    teacher_input: 512
    grayscale_ratio: 0.3


Model:
  checkpoints: ./MODELS/S/best_teacher.pth
  model_size: S
  batch_size: 1
  channel_size: 384
  input_size: 256
  iterations: 50000
  with_bn: false
  


print_freq: 100
category: bottle
normalized_ratio: 0.1
combined_mst_ratio: 0.5
combined_mae_ratio: 0.5
checkpoints_type: auroc
seed: 42
ckpt_dir: ./MODELS/S/
result_dir: ./RESULTS/S/